add filter option by registries
m-cat/cargo-deps pull request #23
Opened 2022-08-16 09:55 UTC by MarcAntoine-Arnaud

I have added the ability to filter by registry to display the graph of dependencies on one or many registry/ies (that can be also private registry).

2022-08-16 11:06 UTC, m-cat commented
Awesome, thank you! Cool option. I'll try to get to a full review today.

2022-08-16 11:07 UTC, m-cat requested changes

2022-08-16 11:07 UTC, m-cat commented on src/args.rs
> +    /// Filter dependencies by registries
Can this include an example of what a valid input would look like?

2022-08-16 11:54 UTC, MarcAntoine-Arnaud commented on src/args.rs
> +    /// Filter dependencies by registries
When you use https://doc.rust-lang.org/cargo/reference/registries.html, you have to define the registry regarding the url of the git crates.  
So it's mostly just a string.
And I have tested, you can use multiple times `registries` option like:

```
cargo deps --registries my-first-registry --registries my-second-registry
```
and it will list only dependencies from these registries.

2022-08-17 08:05 UTC, MarcAntoine-Arnaud commented on src/args.rs
> +    /// Filter dependencies by registries
I have updated the commit, is it better/ok now ?

2022-08-17 11:54 UTC, m-cat commented on src/lib.rs
> +use registries::Registries;
I think this line is not needed.

2022-08-17 11:55 UTC, m-cat approved these changes
Looks good, thank you!

2022-08-17 11:59 UTC, m-cat commented on src/args.rs
> +    /// Filter dependencies by registries
Looks great!

2022-08-17 12:00 UTC, m-cat commented
Do you mind resolving the merge conflicts with `master` please?

2022-08-18 08:35 UTC, MarcAntoine-Arnaud commented on src/lib.rs
> +use registries::Registries;
I have change the import in project, so yes not needed here.

2022-08-18 08:36 UTC, MarcAntoine-Arnaud commented
I have resolved conflicts with `master`, so now it will be fine.
I let you re-review.

2022-08-18 18:33 UTC, m-cat approved these changes

2022-08-18 18:36 UTC, merged